spaceone-dev/docs

content/en/docs/guides/user_guide/service_account/azure_access_control_iam_policy_management.md
Add azure app registration tutorial link
=> docs: Add azure app registration tutorial link

content/en/docs/guides/user_guide/service_account/azure_access_control_iam_policy_management.md
Add user guide for registering app
=> docs: update azure access control iam policy

content/ko/docs/guides/spaceone_cli/_index.md, content/ko/docs/guides/spaceone_cli/managing_role_policy/_index.md, content/ko/docs/guides/spaceone_cli/managing_role_policy/examples.md, content/ko/docs/guides/spaceone_cli/managing_role_policy/managing_policy.md, content/ko/docs/guides/spaceone_cli/managing_role_policy/managing_role.md
- update how to control policy/role using spacectl
=> docs: update spacectl usage

content/en/docs/setup/advanced_configuration/_index.md
=> Add recommended CI size

content/en/docs/_index.md, content/ko/docs/_index.md
=> Change Document to Documentation

layouts/index.html
=> Change mission statement

layouts/partials/toc.html
=> fix: remove title of toc

content/en/docs/setup_operation/operation/_index.md
Add default language and timezone example.
- [v] New Documentation
=> Add setup & operation > operation

content/en/docs/developers/plugins/developer_guide/plugin_debugging/_index.md
- fix overall process in plugin debugging introduction
=> docs: fix overall process

content/en/docs/developers/plugins/developer_guide/plugin_debugging/_index.md, content/en/docs/introduction/release_notes/_index.md
=> docs: rearrange the documentation menu

content/en/docs/developers/api_sdk/_index.md, content/en/docs/developers/api_sdk/api/_index.md
Add developers > API & SDK > API
=> Add API page

content/en/docs/introduction/release_notes/release_note_list/v1.9.1.md, content/ko/docs/introduction/release_notes/release_note_list/v1.9.1.md
=> fix: fix page created date

content/en/docs/introduction/release_notes/release_note_list/v1.9.1.md, content/ko/docs/introduction/release_notes/release_note_list/v1.9.1.md
- Update sequence of heading to improve visibility
=> fix: Modified layer

content/en/docs/introduction/release_notes/release_note_list/v1.9.1.md, content/ko/docs/introduction/release_notes/release_note_list/v1.9.1.md
- Deleted deprecated plugins from supported plugin list table
=> fix: Deleted deprecated plugins

content/en/docs/developers/plugins/developer_guide/_index.md, content/en/docs/developers/plugins/developer_guide/grpc_interface/_index.md, content/en/docs/developers/plugins/developer_guide/plugin_deployment/_index.md, content/en/docs/developers/plugins/developer_guide/plugin_register/_index.md, content/en/docs/guides/advanced/spaceone_cli/_index.md, content/ko/docs/guides/advanced/spaceone_cli/_index.md
- Update spacectl user guide
- Update Plugin developer guide for english edition
=> fix: update spacecli, plugin developerguide for english edition

assets/scss/_navbar.scss, config.toml, content/en/blog/_index.md, content/en/community/_index.md, content/en/docs/_index.md, content/en/get_involved/_index.md, content/en/get_involved/membership/_index.md, content/en/get_involved/plugin_marketplace/_index.md, content/en/get_involved/technical_sterring_comittee/_index.md, content/ko/community/_index.md, content/ko/docs/_index.md, content/ko/get_involved/_index.md, content/ko/get_involved/membership/_index.md, content/ko/get_involved/plugin_marketplace/_index.md, content/ko/get_involved/technical_sterring_comittee/_index.md, layouts/get_involved/baseof.html, layouts/get_involved/list.html, layouts/partials/navbar.html
Add get involved menu to navbar
=> feat: add get-involved menu to navbar

LICENSE, assets/scss/_footer.scss, layouts/partials/footer.html
=> fix: fix CC-BY 4.0 license text in footer

content/en/docs/guides/service_account/aws_service_account_policy_management.md, content/en/docs/guides/service_account/google_cloud_service_account_policy_management.md, content/ko/docs/guides/service_account/alibaba-cloud-service-account-policy-management.md, content/ko/docs/guides/service_account/aws-service-account-policy-management.md, content/ko/docs/guides/service_account/azure-access-control-iam-policy-management.md, content/ko/docs/guides/service_account/google-cloud-service-account-policy-management.md, content/ko/docs/guides/service_account/oracle-cloud-infrastructure-service-account-policy-management.md
- Update service accounts guide to latest inventory plugin versions
=> fix: update policy

content/ko/docs/introduction/release_notes/_index.md, content/ko/docs/introduction/release_notes/release_note_list/v1.9.3.md
=> doc: add 1.9.3 release note

content/ko/docs/introduction/release_notes/release_note_list/v1.9.3.md
=> doc: update 1.9.3 release note

content/en/docs/setup_operation/quick_install/_index.md
- Version of the chart example has been modified.
- Configmap deletion script has been added.
- fix typo
=> fix: Update quick install guide

content/en/docs/introduction/release_notes/_index.md, content/en/docs/introduction/release_notes/release_note_list/v1.9.3.md, content/ko/docs/introduction/release_notes/_index.md
- Added release note of spaceone v1.9.3(eng)
=> doc: update 1.9.3 release note(eng)

content/ko/docs/guides/service_account/_index.md, content/ko/docs/guides/service_account/google-cloud-service-account-policy-management.md
- Updated google cloud service account policy
=> doc: google cloud service account documentation updated

.github/workflows/issu-notion-sync.yml
=> feat: add notion workflow

.github/workflows/issue-notion-sync.yml
=> fix: rename of file name

content/ko/docs/introduction/release_notes/_index.md
- [V] Fix Content
Fix errata in index
=> Korean 1.9.4 release note index fix v2

content/en/docs/introduction/release_notes/_index.md, content/en/docs/introduction/release_notes/release_note_list/v1.9.4.md
New English release note for 1.9.4 version 
Indent fixed on Korean release note for 1.9.4 version
=> English 1.9.4 release note

content/en/docs/introduction/release_notes/_index.md, content/en/docs/introduction/release_notes/release_note_list/v1.9.4.md
Fix errata on 1.9.4. English release note
=> English 1.9.4 release note and index file v2

content/en/docs/setup_operation/quick_install/_index.md
=> Update minikube manual

content/ko/docs/guides/alert_manager/webhook_settings/aws_sns_webhook.md
Signed-off-by: Seolmin Kwon <seolmin@megazone.com>
Fixed incorrect formatting and readability.
=> docs: change sns webhook setting guideline in korean

config.toml, content/en/docs/_index.md, content/en/docs/introduction/release_notes/_index.md, content/en/docs/introduction/release_notes/release_note_list/v1.9.6.md, content/ko/get_involved/_index.md
new v1.9.6 english release note
=> doc: v1.9.6 eng release note

content/ko/docs/developers/frontend/coding_style/_index.md
Add frontend coding style ( docs > developers > frontend > coding_style )
Every pointing out is welcome
=> docs: add frontend coding style

content/en/docs/developers/frontend/software_design/authentication/_index.md, content/en/docs/developers/frontend/software_design/error_handling/_index.md
=> docs: add 'error handling' docs

content/en/docs/introduction/release_notes/_index.md, content/en/docs/introduction/release_notes/release_note_list/v1.9.7.md, content/ko/docs/introduction/release_notes/_index.md, content/ko/docs/introduction/release_notes/release_note_list/v1.9.7.md
- New release note (1.9.7) added
=> New release note added

content/en/community/_index.md, content/ko/community/_index.md, layouts/community/list.html
=> feat: add korean translations to community page

config.toml, layouts/robots.txt
=> feat: add robots.txt for SEO

config.toml, layouts/robots.txt
=> feat: change robots.txt and add sitemap for SEO

layouts/robots.txt, static/googlea5f11c86a6d2433c.html
=> fix: robots.txt file

static/googlea5f11c86a6d2433c.html
=> fix: remove google search console verification file

content/en/docs/guides/project/quick-start.md, content/ko/docs/guides/getting-started/project-setup.md, content/ko/docs/guides/getting-started/quick-start.md, content/ko/docs/guides/getting-started/user-setup.md, content/ko/docs/guides/project/member.md, content/ko/docs/guides/project/project-group.md, content/ko/docs/guides/project/project.md, content/ko/docs/guides/project/quick-start.md
=> docs: add getting started(except service account setup), project guide

content/ko/docs/guides/getting-started/project-setup.md, content/ko/docs/guides/getting-started/quick-start.md, content/ko/docs/guides/getting-started/user-setup.md, content/ko/docs/guides/project/member.md, content/ko/docs/guides/project/project-group.md, content/ko/docs/guides/project/project.md
=> docs: add page descriptions to getting started setups,  project

assets/scss/_breadcrumb.scss, assets/scss/_content.scss, assets/scss/_main-container.scss, assets/scss/_sidebar-toc.scss, assets/scss/_sidebar-tree.scss
=> feat: add style to documentation

assets/scss/_content.scss, assets/scss/_index.scss, content/ko/docs/guides_v1/getting_started/style-test.md
=> style: add style to documentation

content/ko/docs/guides/asset-inventory/cloud-service.md, content/ko/docs/guides/asset-inventory/collector.md, content/ko/docs/guides/asset-inventory/server.md, content/ko/docs/guides/getting-started/project-setup.md, content/ko/docs/guides/getting-started/user-setup.md, content/ko/docs/guides/project/member.md, content/ko/docs/guides/project/project-group.md, content/ko/docs/guides/project/project.md
=> docs: add asset inventory guide (text only)

content/ko/docs/guides/administration/_index.md, content/ko/docs/guides/administration/iam-policy.md, content/ko/docs/guides/administration/iam-user.md, content/ko/docs/guides/advanced/_index.md, content/ko/docs/guides/alert-manager/_index.md, content/ko/docs/guides/asset-inventory/cloud-service.md, content/ko/docs/guides/asset-inventory/collector.md, content/ko/docs/guides/asset-inventory/server.md, content/ko/docs/guides/asset-inventory/service-account.md, content/ko/docs/guides/getting-started/_index.md, content/ko/docs/guides/getting-started/project-setup.md, content/ko/docs/guides/getting-started/service-account-setup.md, content/ko/docs/guides/getting-started/user-setup.md, content/ko/docs/guides/plugins/_index.md, content/ko/docs/guides/plugins/alert-manager-notification.md, content/ko/docs/guides/plugins/alert-manager-webhook.md, content/ko/docs/guides/plugins/asset-inventory-collector.md, content/ko/docs/guides/plugins/cost-explorer-data-source.md, content/ko/docs/guides/plugins/iam-authentication.md, content/ko/docs/guides/project/_index.md, content/ko/docs/guides/project/member.md, content/ko/docs/guides/project/project-group.md, content/ko/docs/guides/project/project.md
=> docs: add project index and update titles in guide

content/ko/docs/developers/design_system/_index.md
=> feat: add design system docs

assets/scss/_content.scss, assets/scss/section-index.scss, layouts/partials/section-index.html
=> style: add style to entry page

assets/scss/_content.scss, assets/scss/_footer.scss, assets/scss/_index.scss, assets/scss/_main-container.scss, assets/scss/_nav.scss, assets/scss/_navbar.scss, assets/scss/_sidebar-toc.scss, assets/scss/_sidebar-tree.scss, assets/scss/_variables_project.scss, assets/scss/section-index.scss, config.toml, content/ko/community/_index.md, content/ko/docs/_index.md, content/ko/docs/concepts/_index.md, content/ko/docs/developers/_index.md, content/ko/docs/guides/_index.md, content/ko/docs/guides_v1/_index.md, content/ko/docs/introduction/_index.md, content/ko/docs/setup_operation/_index.md, i18n/en.toml, i18n/ko.toml, layouts/docs/baseof.html, layouts/docs/content.html, layouts/docs/list.html, layouts/partials/footer.html, layouts/partials/navbar-version-selector.html, layouts/partials/navbar.html, layouts/partials/section-index.html, layouts/partials/toc.html
=> style: add style to documentation page

.gitignore
=> fix: edit .gitignore

assets/scss/_content.scss, assets/scss/_footer.scss, assets/scss/_navbar.scss, assets/scss/_sidebar-tree.scss, assets/scss/_variables_project.scss, layouts/partials/footer.html, static/images/documentation/ic_chevron-down.svg
- fix sidebar 
- change Roboto to Pretendard
=> feat: fix sidebar in documentation

assets/scss/_content.scss, content/en/docs/developers/contribute/documentation/style_guide.md, content/en/docs/guides_v1/advanced/automation/power_scheduler.md, content/en/docs/guides_v1/getting_started/power_scheduler_quick_start.md, content/en/docs/guides_v1/service_account/_index.md, content/ko/docs/developers/contribute/document/style_guide.md, content/ko/docs/guides_v1/advanced/automation/power_scheduler.md
=> style: fix style of button, anchor, code

assets/scss/_index.scss
Resolves button align style issue
=> style: apply default font

content/ko/docs/guides/asset-inventory/service-account.md
=> docs: add link & fix typo

content/ko/docs/guides/administration/iam-role.md, content/ko/docs/guides/alert-manager/dashboard.md, content/ko/docs/guides/alert-manager/quick-start.md
=> fix: fix contents of alert-manager guide

assets/js/toc.js, assets/scss/section-index.scss, layouts/partials/navbar.html, layouts/partials/scroll.html, layouts/partials/toc.html
=> feat: add toc.js for scrolling

content/ko/docs/guides/alert-manager/notification.md, content/ko/docs/guides/getting-started/_index.md
=> fix: edit notification guide

content/ko/docs/guides/cost-explorer/dashboard.md
=> fix: edit tag management content in all guides

content/ko/docs/guides/plugins/alert-manager-webhook.md
Signed-off-by: Seolmin Kwon <seolmin@megazone.com>
=> bugfix: fix alert manager webhook

content/ko/docs/guides/plugins/alert-manager-notification.md, content/ko/docs/guides/plugins/alert-manager-webhook.md, content/ko/docs/guides/plugins/asset-inventory-collector.md, content/ko/docs/guides/plugins/cost-explorer-data-source.md, content/ko/docs/guides/plugins/iam-authentication.md
Signed-off-by: Seolmin Kwon <seolmin@megazone.com>
=> docs: fix overview of plugins

content/ko/docs/guides/alert-manager/alert.md
=> fix: edit alert guides

README.md
=> docs: update build information

content/en/docs/introduction/release_notes/_index.md, content/en/docs/introduction/release_notes/release_note_list/v1.10.0.md, content/ko/docs/introduction/release_notes/release_note_list/v1.10.0.md
New English release note for v1.10.0 and some updates with Korean version
=> new: v1.10.0 english release note
